FROM meteorhacks/meteord:devbuild



docker run -d -p 80:80 -v /home/remip/manifmaker/manifmaker:/bundle meteorhacks/meteord:devbuild 


docker run --rm -e ROOT_URL=http://assomaker.leomartinez.fr -e REPO=https://github.com/assomaker/manifmaker -e BRANCH=deploy ulexus/meteor



docker run --rm -e ROOT_URL=http://assomaker.leomartinez.fr -v /home/remip/manifmaker/manifmaker:/src/app ulexus/meteor