FROM mongo:3.2.20

ADD create_backup_mongo_user.js /docker-entrypoint-initdb.d/create_backup_mongo_user.js
ADD create_manifmaker_mongo_user.js /docker-entrypoint-initdb.d/create_manifmaker_mongo_user.js