FROM mongo:3.2.6

ADD create_backup_mongo_user.js /scripts/create_backup_mongo_user.js
ADD create_manifmaker_mongo_user.js /scripts/create_manifmaker_mongo_user.js

# TODO add entrypoint to run scripts once db is up